// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlow4V5iVLHGuRamztoZQXVSbp9tGSOs',
    appId: '1:994435974311:web:2304f30dc07b5977050782',
    messagingSenderId: '994435974311',
    projectId: 'securoutine',
    authDomain: 'securoutine.firebaseapp.com',
    storageBucket: 'securoutine.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrLLt9CtJQArA_owICD9cru18L97pN0a0',
    appId: '1:994435974311:android:c01e79837ae094ee050782',
    messagingSenderId: '994435974311',
    projectId: 'securoutine',
    storageBucket: 'securoutine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXpO4Ut3HZFthIREr8_-DnjTY0v65Dw3Q',
    appId: '1:994435974311:ios:a267dbb5a54e50ff050782',
    messagingSenderId: '994435974311',
    projectId: 'securoutine',
    storageBucket: 'securoutine.firebasestorage.app',
    iosClientId: '994435974311-5plvj4j6fg405v9skf68mvt43kgo1i9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXpO4Ut3HZFthIREr8_-DnjTY0v65Dw3Q',
    appId: '1:994435974311:ios:a267dbb5a54e50ff050782',
    messagingSenderId: '994435974311',
    projectId: 'securoutine',
    storageBucket: 'securoutine.firebasestorage.app',
    iosClientId: '994435974311-5plvj4j6fg405v9skf68mvt43kgo1i9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZlow4V5iVLHGuRamztoZQXVSbp9tGSOs',
    appId: '1:994435974311:web:2304f30dc07b5977050782',
    messagingSenderId: '994435974311',
    projectId: 'securoutine',
    authDomain: 'securoutine.firebaseapp.com',
    storageBucket: 'securoutine.firebasestorage.app',
  );
}
